package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
	"graphql-golang/graph/generated"
	"graphql-golang/graph/model"

	"github.com/confluentinc/confluent-kafka-go/kafka"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	broker := "localhost:9092"
	topic1 := "test1"

	// Create a producer
	producer, err := kafka.NewProducer(&kafka.ConfigMap{"bootstrap.servers": broker})
	if err != nil {
		panic(err)
	}

	deliveryChan := make(chan kafka.Event)
	// Produce a message to the topic
	value := "hello, world 11"
	err = producer.Produce(&kafka.Message{
		TopicPartition: kafka.TopicPartition{Topic: &topic1, Partition: 0},
		Value:          []byte(value),
	}, deliveryChan)
	if err != nil {
		panic(err)
	}
	e := <-deliveryChan
	m := e.(*kafka.Message)
	if m.TopicPartition.Error != nil {
		fmt.Printf("Delivery failed: %v", m.TopicPartition.Error)
	}
	close(deliveryChan)
	producer.Close()

	// =================================================================
	config := &kafka.ConfigMap{
		"bootstrap.servers":                     "localhost:9092",
		"group.id":                              "test-group",
		"go.application.rebalance.enable":       true,
		"max.in.flight.requests.per.connection": 1,
	}

	// Create consumer
	consumer, err := kafka.NewConsumer(config)
	if err != nil {
		panic(err)
	}
	defer consumer.Close()

	topic := "test1"
	var user = &model.User{}
	consumer.SubscribeTopics([]string{topic}, nil)
	run := true
	for run {
		msg, err := consumer.ReadMessage(-1)
		if err == nil {
			fmt.Printf("Message on %s: %s\n", msg.TopicPartition, string(msg.Value))
			run = false
			com, err := consumer.CommitMessage(msg)
			fmt.Println("Something right here", com, err)
			if err != nil {
				fmt.Println("Error", err)
			}
		} else {
			// The client will automatically try to recover from all errors.
			fmt.Printf("Consumer error: %v (%v)\n", err, msg)
		}
	}

	return user, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
